debugging gha

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -33,12 +33,16 @@ jobs:
             - name: Set up Node
               uses: actions/setup-node@v3
               with:
-                  node-version: 18
+                  node-version-file: '.nvmrc'
                   cache: "npm"
             - name: Install dependencies
               run: npm install
             - name: Build
               run: npm run build
+            - name: List build output
+              run: |
+                ls -la
+                ls -la dist || echo "dist directory not found!"
             - name: Setup Pages
               uses: actions/configure-pages@v3
             - name: Upload artifact
@@ -48,4 +52,4 @@ jobs:
                   path: "./dist"
             - name: Deploy to GitHub Pages
               id: deployment
-              uses: actions/deploy-pages@v1
+              uses: actions/deploy-pages@v2
